### ISSUE TITLE
关于复现进度

### ISSUE THREAD

**Issue by ZainZhao** [1051003502/CFGAN#1]
你好，请问现在代码复现完成了吗

**Comment by 1051003502** [comment]
代码能跑，但是有很多地方还不完善。

**Comment by ZainZhao** [comment]
您好，非常感谢，您说的不完善能不能举几个例子

**Comment by 1051003502** [comment]
user-oriented版本有   item-oriented无
CF methods只有CFGAN−ZP
评测只有准确度
只适用于GPU    CPU没考虑

**Comment by ZainZhao** [comment]
哦哦，好的，多谢

**Comment by ZainZhao** [comment]
您好，我看了您的代码，请问是基于作者的代码提出来的吗？

**Comment by 1051003502** [comment]
是的。 你参考这个代码是要做什么呀？

**Comment by ZainZhao** [comment]
我最近在做本科的毕设，您能不能给我提供一下作者的源码呢

**Comment by ZainZhao** [comment]
非常感谢

**Comment by 1051003502** [comment]
你加我QQ    1051003502
