### ISSUE TITLE
关于recall指标的计算

### ISSUE THREAD

**Issue by stormDL** [1051003502/CFGAN#4]
你好，我认为你的recall指标计算有误，recall的计算公式如下：
$$
recall = \frac{\sum_{u\in U}|R(u)\cap T(u)|}{\sum_{u\in U}|T(u)|}
$$
而你代码的实现却是如下公式：
$$
recall = \frac{\sum_{u\in U}\frac{|R(u)\cap T(u)|}{|T(u)|}}{|U|}
$$
如果我的理解有误，那请不吝赐教😃

**Comment by 1051003502** [comment]
召回率是针对原来的样本而言的，它表示的是样本中的正例有多少被预测正确了。
代码中是  hit/len(groundTruth)     hit很容易理解，groundTruth里面是所有期望被推荐的物品（来自于u2.test），这里应该没有问题。
你可以仔细看看加载进来的数据。

**Comment by stormDL** [comment]
你说的这个意思我能理解，也许是我的问题没有表述清楚，下面我用一个例子来说明一下：

1. 假设现在存在两个用户，用户1真实购买了{A、B、C}三个物品，用户2真实购买了{C、D}两个物品。
2. 假设对每个用户做出 2 个物品的推荐，即topN=2
3. 系统预测出用户1会购买{A、D}，用户2会购买{D、B}

如果用你的方法来计算那么就是： recall = (1/3 + 1/2) / 2 = 5/12
如果用我在最开始写的来算那么就是：recall = (1+1)/(3+2) = 2/5

你在代码当中的实现是计算**每个用户的recall**然后求和，最后求平均值；

难道recall不是相对于所有项目而言？即计算所有用户真实购买的项目数量（上述例子是 3+2），然后把每个用户hit相加(上述例子是 1+1)，然后这样来计算“样本中的正例有多少被预测正确了”这个指标。

Ps.在最开始提问的latex公式中可以看清楚两者之间的区别

**Comment by 1051003502** [comment]
那就只好给recall改个名字了，叫做平均召回率吧。
我觉得这样计算可以更好的评价算法的性能，比如 （1/2+1/10）/2=0.3     (1+1)/(2+10)=0.167
这里面的两个1命中难度是不一样的，2个命中1个显然比10个命中1个要难，那这两个1怎么可以同等对待相加起来呢？
总结来说我的recall计算不是标准的recall，但是我认为这样计算更加合理。

**Comment by stormDL** [comment]
谢谢你的回复，我明白了。你的这种计算方法确实更加合理~
